### ISSUE TITLE
Error found about "position_net"

### ISSUE THREAD

**Issue by Kenneth-Wong** [jiuntian/sd-webui-interactdiffusion#1]
Thanks for your great work. But when I start the webUI using your ckpt, there raises an error: 

Traceback (most recent call last):
  File "/home/wwb/code/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/wwb/code/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/home/wwb/code/stable-diffusion-webui/modules/launch_utils.py", line 464, in start
    webui.webui()
  File "/home/wwb/code/stable-diffusion-webui/webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "/home/wwb/code/stable-diffusion-webui/modules/ui.py", line 263, in create_ui
    scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "/home/wwb/code/stable-diffusion-webui/modules/scripts.py", line 523, in initialize_scripts
    script = script_data.script_class()
  File "/home/wwb/code/stable-diffusion-webui/extensions/sd-webui-interactdiffusion/scripts/interactiduffison_ui.py", line 196, in __init__
    shared.pluggable_ID = PluggableInteractDiffusion(shared.sd_model.model.diffusion_model,interactdiffusion_state_dict)
  File "/home/wwb/code/stable-diffusion-webui/extensions/sd-webui-interactdiffusion/scripts/interactdiffusion_pluggable.py", line 299, in __init__
    raise Exception('State dict for position_net is not correct')
Exception: State dict for position_net is not correct

**Comment by jiuntian** [comment]
Hi,

Thanks for feedback. The extension currently only support SD v1.x and did not support SD XL and SD v2. I have update the error message so that it can better convey the error caused.
